// src/pages/Landing.tsx
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowDown } from 'lucide-react';
import { motion } from 'framer-motion';

import { Navbar, Footer, WhatsAppButton } from '@/components/layout';
import { ParticleBackground, FadeInUp, StaggerContainer } from '@/components/animations';
import { Button, Card, Badge } from '@/components/ui';
import { ContactForm } from '@/components/shared/ContactForm';

import { serviciosService } from '@/services/servicios.service';
import { portafolioService } from '@/services/portafolio.service';
import { blogService } from '@/services/blog.service';

import { Servicio, Evento, Post } from '@/types';

export const Landing = () => {
  const [servicios, setServicios] = useState<Servicio[]>([]);
  const [eventosDestacados, setEventosDestacados] = useState<Evento[]>([]);
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const loadData = async () => {
      try {
        const [svc, eventos, blog] = await Promise.all([
          serviciosService.getServicios(),
          portafolioService.getEventos(undefined, true),
          blogService.getPosts(3),
        ]);
        setServicios(svc);
        setEventosDestacados(eventos);
        setPosts(blog);
      } catch (error) {
        console.error('Error loading landing data:', error);
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-surface flex items-center justify-center">
        <div className="text-center">
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 2, repeat: Infinity }}
            className="w-12 h-12 border-2 border-primary border-t-transparent rounded-full mx-auto mb-4"
          />
          <p className="text-muted">Cargando experiencia...</p>
        </div>
      </div>
    );
  }

  return (
    <>
      <Navbar />
      <WhatsAppButton />

      {/* Hero Section */}
      <section className="relative min-h-screen bg-surface pt-20 overflow-hidden flex items-center">
        <ParticleBackground />
        <div className="relative z-10 max-w-7xl mx-auto px-4 text-center py-32">
          <FadeInUp>
            <h1 className="text-5xl md:text-7xl font-bebas tracking-wider mb-6 text-text">
              CREAMOS EXPERIENCIAS
              <br />
              <span className="gradient-primary bg-clip-text text-transparent">
                INOLVIDABLES
              </span>
            </h1>
          </FadeInUp>

          <FadeInUp delay={0.2}>
            <p className="text-lg md:text-xl text-muted max-w-2xl mx-auto mb-12">
              Desde lo corporativo hasta lo más social. Cada evento es una oportunidad para brillar.
              Orion transforma tus ideas en realidad con producción de clase mundial.
            </p>
          </FadeInUp>

          <FadeInUp delay={0.4}>
            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
              <Button onClick={() => navigate('/portafolio')}>
                Ver Portafolio
              </Button>
              <Button
                variant="outline"
                onClick={() =>
                  document.querySelector('#cotizacion')?.scrollIntoView({ behavior: 'smooth' })
                }
              >
                Cotiza tu evento
              </Button>
            </div>
          </FadeInUp>

          <motion.div
            animate={{ y: [0, 10, 0] }}
            transition={{ duration: 2, repeat: Infinity }}
            className="mt-16"
          >
            <ArrowDown className="text-primary mx-auto" size={32} />
          </motion.div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-20 bg-card/50 relative">
        <div className="max-w-7xl mx-auto px-4">
          <StaggerContainer>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
              {[
                { number: '+150', label: 'Eventos realizados' },
                { number: '+8', label: 'Años de experiencia' },
                { number: '+80', label: 'Clientes satisfechos' },
                { number: '+20', label: 'Ciudades alcanzadas' },
              ].map((stat, idx) => (
                <FadeInUp key={idx} delay={idx * 0.1}>
                  <div className="text-center">
                    <div className="relative">
                      <div className="text-6xl md:text-7xl font-bebas text-primary/10 absolute inset-0 flex items-center justify-center">
                        {stat.number}
                      </div>
                      <div className="text-4xl md:text-5xl font-bebas text-primary relative">
                        {stat.number}
                      </div>
                    </div>
                    <p className="text-muted mt-4 text-sm">{stat.label}</p>
                  </div>
                </FadeInUp>
              ))}
            </div>
          </StaggerContainer>
        </div>
      </section>

      {/* Services Section */}
      <section className="py-20 bg-surface">
        <div className="max-w-7xl mx-auto px-4">
          <FadeInUp>
            <h2 className="section-title text-center mb-16">LO QUE HACEMOS</h2>
          </FadeInUp>

          <StaggerContainer staggerDelay={0.05}>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {servicios.slice(0, 6).map((servicio) => (
                <FadeInUp key={servicio.id}>
                  <Card>
                    <Badge variant="secondary" className="mb-4">
                      {servicio.nombre.split(' ')[0]}
                    </Badge>
                    <h3 className="text-xl font-grotesk font-bold text-text mb-3">
                      {servicio.nombre}
                    </h3>
                    <p className="text-sm text-muted leading-relaxed">
                      {servicio.descripcion_corta}
                    </p>
                  </Card>
                </FadeInUp>
              ))}
            </div>
          </StaggerContainer>
        </div>
      </section>

      {/* Portfolio Preview */}
      <section className="py-20 bg-card/50">
        <div className="max-w-7xl mx-auto px-4">
          <FadeInUp>
            <h2 className="section-title text-center mb-16">NUESTRO TRABAJO</h2>
          </FadeInUp>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-12">
            {eventosDestacados.slice(0, 4).map((evento, idx) => (
              <FadeInUp key={evento.id} delay={idx * 0.1}>
                <Link to={`/portafolio/${evento.slug}`}>
                  <Card className="h-72 overflow-hidden group cursor-pointer">
                    <div
                      className="w-full h-full bg-cover bg-center relative group-hover:scale-105 transition-transform duration-300"
                      style={{
                        backgroundImage: `url('${evento.imagen_destacada}')`,
                      }}
                    >
                      <div className="gradient-overlay absolute inset-0 group-hover:opacity-50 transition-opacity duration-300 flex flex-col justify-end p-6">
                        <Badge variant="secondary" className="mb-3 w-fit">
                          {evento.tipo_id}
                        </Badge>
                        <h3 className="text-xl font-grotesk font-bold text-text">
                          {evento.nombre}
                        </h3>
                        <p className="text-sm text-muted mt-2">{evento.lugar}</p>
                      </div>
                    </div>
                  </Card>
                </Link>
              </FadeInUp>
            ))}
          </div>

          <div className="text-center">
            <Button onClick={() => navigate('/portafolio')} variant="outline">
              Ver todo el portafolio
            </Button>
          </div>
        </div>
      </section>

      {/* Blog Preview */}
      <section className="py-20 bg-surface">
        <div className="max-w-7xl mx-auto px-4">
          <FadeInUp>
            <h2 className="section-title text-center mb-16">DESDE EL EQUIPO</h2>
          </FadeInUp>

          <StaggerContainer>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {posts.map((post, idx) => (
                <FadeInUp key={post.id} delay={idx * 0.1}>
                  <Link to={`/blog/${post.slug}`}>
                    <Card className="h-full overflow-hidden group cursor-pointer">
                      <div
                        className="w-full h-48 bg-cover bg-center mb-4 rounded group-hover:scale-110 transition-transform duration-300"
                        style={{
                          backgroundImage: `url('${post.imagen_destacada}')`,
                        }}
                      />
                      <Badge variant="primary" className="mb-3">
                        Blog
                      </Badge>
                      <h3 className="text-lg font-grotesk font-bold text-text mb-2">
                        {post.titulo}
                      </h3>
                      <p className="text-sm text-muted line-clamp-2">{post.extracto}</p>
                      <p className="text-xs text-muted mt-4">Leer más →</p>
                    </Card>
                  </Link>
                </FadeInUp>
              ))}
            </div>
          </StaggerContainer>
        </div>
      </section>

      {/* CTA Section */}
      <section id="cotizacion" className="py-20 gradient-primary">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <FadeInUp>
            <h2 className="text-4xl md:text-6xl font-bebas text-white mb-6">
              ¿TIENES UN EVENTO EN MENTE?
            </h2>
          </FadeInUp>

          <FadeInUp delay={0.2}>
            <p className="text-lg text-white/90 mb-12">
              Cuéntanos tu idea y te contactamos en menos de 24 horas
            </p>
          </FadeInUp>

          <FadeInUp delay={0.4}>
            <ContactForm />
          </FadeInUp>
        </div>
      </section>

      <Footer />
    </>
  );
};

// frontend-vue/src/views/Landing.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { RouterLink } from 'vue-router';
import ContactForm from '@/components/ContactForm.vue';
import ServicioModal from '@/components/ServicioModal.vue';
import FadeInUp from '@/components/animations/FadeInUp.vue';
import ParticleBackground from '@/components/animations/ParticleBackground.vue';
import { useReducedMotion } from '@/composables/useReducedMotion';
import { serviciosService } from '@/services/servicios';
import { portafolioService } from '@/services/portafolio';
import { blogService } from '@/services/blog';
import type { Servicio, Evento, Post, FotoEvento } from '@/types';

const servicios = ref<Servicio[]>([]);
const eventosDestacados = ref<Evento[]>([]);
const posts = ref<Post[]>([]);

const servicioModalRef = ref<InstanceType<typeof ServicioModal> | null>(null);
const abrirServicio = (svc: Servicio) => servicioModalRef.value?.abrir(svc);

const prefersReducedMotion = useReducedMotion();

// Carrusel de servicios: ventana de N items visibles calculada por indice
// (modulo), sin duplicar el arreglo — evita que un mismo servicio aparezca
// repetido en pantalla. Avanzar mueve el indice +1; al pasar el ultimo
// vuelve a 0 (el "final a la izquierda reaparece a la derecha").
const SERVICIOS_VISIBLES = 4;
const servicioInicio = ref(0);
let servicioAutoTimer: ReturnType<typeof setInterval> | undefined;

const serviciosVisibles = computed(() => {
  const total = servicios.value.length;
  if (!total) return [];
  const n = Math.min(SERVICIOS_VISIBLES, total);
  return Array.from({ length: n }, (_, i) => servicios.value[(servicioInicio.value + i) % total]);
});

const servicioSiguiente = () => {
  if (!servicios.value.length) return;
  servicioInicio.value = (servicioInicio.value + 1) % servicios.value.length;
};
const servicioAnterior = () => {
  if (!servicios.value.length) return;
  servicioInicio.value = (servicioInicio.value - 1 + servicios.value.length) % servicios.value.length;
};

const detenerAutoServicios = () => {
  if (servicioAutoTimer) {
    clearInterval(servicioAutoTimer);
    servicioAutoTimer = undefined;
  }
};
const iniciarAutoServicios = () => {
  detenerAutoServicios();
  if (prefersReducedMotion.value || servicios.value.length <= SERVICIOS_VISIBLES) return;
  servicioAutoTimer = setInterval(servicioSiguiente, 3500);
};
const avanzarManual = (fn: () => void) => {
  fn();
  iniciarAutoServicios();
};

// Empresas "que confian en nosotros" — placeholder por ahora, reemplazar
// por logos reales (misma clase .empresa-logo funciona igual con <img>).
const empresasConfianza = [
  { nombre: 'Aurora Corp', color: '#e63946' },
  { nombre: 'Nimbus Group', color: '#2a9d8f' },
  { nombre: 'Vértice SA', color: '#e9c46a' },
  { nombre: 'Solaris Ltda', color: '#f4a261' },
  { nombre: 'Prisma Eventos', color: '#457b9d' },
  { nombre: 'Zenith Co', color: '#8338ec' },
];

// Galeria de fotos de eventos: mosaico aleatorio con tamaños variados.
interface FotoGaleria extends FotoEvento {
  eventoNombre: string;
}
const fotosGaleria = ref<FotoGaleria[]>([]);
const fotoGaleriaActiva = ref<string | null>(null);
const TAMANOS_MOSAICO = ['', 'tam-ancho', 'tam-alto', '', 'tam-grande', '', 'tam-alto', 'tam-ancho', '', '', 'tam-ancho', 'tam-alto'];
const tamanoMosaico = (idx: number) => TAMANOS_MOSAICO[idx % TAMANOS_MOSAICO.length];

const stats = [
  { n: '+150', l: 'Eventos realizados' },
  { n: '+8', l: 'Años de experiencia' },
  { n: '+80', l: 'Clientes satisfechos' },
  { n: '+20', l: 'Ciudades alcanzadas' },
];

onMounted(async () => {
  try {
    const [todosServicios, todosEventos, todosPosts] = await Promise.all([
      serviciosService.getServicios(),
      portafolioService.getEventos(),
      blogService.getPosts(3),
    ]);
    servicios.value = todosServicios;
    eventosDestacados.value = todosEventos.filter((e) => e.destacado).slice(0, 4);
    posts.value = todosPosts;

    const pool: FotoGaleria[] = [];
    for (const ev of todosEventos) {
      for (const f of ev.fotos ?? []) {
        if (f.imagen_url) pool.push({ ...f, eventoNombre: ev.nombre });
      }
    }
    for (let i = pool.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [pool[i], pool[j]] = [pool[j], pool[i]];
    }
    fotosGaleria.value = pool.slice(0, 16);

    iniciarAutoServicios();
  } catch (e) {
    console.error('Error cargando landing:', e);
  }
});

onBeforeUnmount(detenerAutoServicios);
</script>

<template>
  <section class="py-5 text-center position-relative overflow-hidden">
    <ParticleBackground />
    <div class="container py-5 position-relative" style="z-index: 1">
      <FadeInUp>
        <h1 class="display-3 fw-bold">CREAMOS EXPERIENCIAS<br /><span class="text-orion-primary">INOLVIDABLES</span></h1>
      </FadeInUp>
      <FadeInUp :delay="0.2">
        <p class="lead text-secondary mx-auto mt-3" style="max-width: 640px">
          Desde lo corporativo hasta lo más social. Orion transforma tus ideas en realidad.
        </p>
      </FadeInUp>
      <FadeInUp :delay="0.4">
        <div class="d-flex gap-3 justify-content-center mt-4">
          <RouterLink to="/portafolio" class="btn btn-orion btn-lg">Ver Portafolio</RouterLink>
          <RouterLink :to="{ path: '/', hash: '#cotizacion' }" class="btn btn-outline-light btn-lg">Cotiza tu evento</RouterLink>
        </div>
      </FadeInUp>
    </div>
  </section>

  <section class="py-5 bg-black bg-opacity-25">
    <div class="container">
      <div class="row text-center">
        <div v-for="(s, idx) in stats" :key="s.l" class="col-6 col-md-3 mb-3">
          <FadeInUp :delay="idx * 0.1">
            <div class="display-5 fw-bold text-orion-primary">{{ s.n }}</div>
            <div class="text-secondary small">{{ s.l }}</div>
          </FadeInUp>
        </div>
      </div>
    </div>
  </section>

  <section class="py-4">
    <div class="container">
      <p class="text-center text-secondary small text-uppercase mb-4">Confían en nosotros</p>
      <div class="d-flex flex-wrap justify-content-center align-items-center gap-4 gap-md-5">
        <div v-for="e in empresasConfianza" :key="e.nombre" class="empresa-logo" :style="{ color: e.color }">
          {{ e.nombre }}
        </div>
      </div>
    </div>
  </section>

  <section class="py-5 overflow-hidden">
    <div class="container">
      <h2 class="text-center fw-bold mb-5">LO QUE HACEMOS</h2>
      <div v-if="servicios.length" class="d-flex align-items-center justify-content-center gap-2"
        @mouseenter="detenerAutoServicios" @mouseleave="iniciarAutoServicios">
        <button v-if="servicios.length > SERVICIOS_VISIBLES" type="button" class="btn btn-outline-light btn-sm flex-shrink-0"
          @click="avanzarManual(servicioAnterior)">‹</button>
        <div class="servicios-carousel-viewport">
          <TransitionGroup name="servicio-slide" tag="div" class="d-flex gap-3 justify-content-center">
            <div v-for="svc in serviciosVisibles" :key="svc.id" class="servicio-carousel-item">
              <div class="card bg-dark border-secondary hover-scale" style="width: 15rem; cursor: pointer"
                @click="abrirServicio(svc)">
                <div class="card-cover rounded-top" style="height: 10rem"
                  :style="svc.imagen_url ? { backgroundImage: `url('${svc.imagen_url}')` } : {}"></div>
                <div class="card-body text-center">
                  <span class="badge text-bg-warning mb-2">{{ svc.nombre.split(' ')[0] }}</span>
                  <h6 class="card-title mb-0">{{ svc.nombre }}</h6>
                </div>
              </div>
            </div>
          </TransitionGroup>
        </div>
        <button v-if="servicios.length > SERVICIOS_VISIBLES" type="button" class="btn btn-outline-light btn-sm flex-shrink-0"
          @click="avanzarManual(servicioSiguiente)">›</button>
      </div>
    </div>
  </section>

  <section class="py-5 bg-black bg-opacity-25">
    <div class="container">
      <h2 class="text-center fw-bold mb-5">NUESTRO TRABAJO</h2>
      <div class="row g-4">
        <div v-for="ev in eventosDestacados" :key="ev.id" class="col-md-6">
          <RouterLink :to="`/portafolio/${ev.slug}`" class="text-decoration-none">
            <div class="card border-0 card-cover d-flex justify-content-end"
              :style="ev.imagen_url ? { backgroundImage: `url('${ev.imagen_url}')` } : {}">
              <div class="p-3" style="background: linear-gradient(0deg, rgba(0,0,0,0.85), transparent)">
                <h5 class="text-white mb-0">{{ ev.nombre }}</h5>
                <small class="text-secondary">{{ ev.lugar }}</small>
              </div>
            </div>
          </RouterLink>
        </div>
      </div>
      <div class="text-center mt-4">
        <RouterLink to="/portafolio" class="btn btn-outline-light">Ver todo el portafolio</RouterLink>
      </div>
    </div>
  </section>

  <section class="py-5">
    <div class="container">
      <h2 class="text-center fw-bold mb-5">DESDE EL EQUIPO</h2>
      <div class="row g-4">
        <div v-for="p in posts" :key="p.id" class="col-md-4">
          <RouterLink :to="`/blog/${p.slug}`" class="text-decoration-none">
            <div class="card h-100 bg-dark border-secondary">
              <div class="card-cover" style="height: 12rem" :style="p.imagen_url ? { backgroundImage: `url('${p.imagen_url}')` } : {}"></div>
              <div class="card-body">
                <span class="badge text-bg-danger mb-2">Blog</span>
                <h6 class="card-title">{{ p.titulo }}</h6>
                <p class="card-text text-secondary small">{{ p.extracto }}</p>
              </div>
            </div>
          </RouterLink>
        </div>
      </div>
    </div>
  </section>

  <section v-if="fotosGaleria.length" class="py-5 bg-black bg-opacity-25">
    <div class="container">
      <h2 class="text-center fw-bold mb-5">MOMENTOS QUE CREAMOS</h2>
      <div class="galeria-mosaico">
        <div v-for="(f, idx) in fotosGaleria" :key="f.id"
          class="galeria-item" :class="[tamanoMosaico(idx), { 'galeria-item-activa': fotoGaleriaActiva === f.id }]"
          @click="fotoGaleriaActiva = fotoGaleriaActiva === f.id ? null : f.id">
          <div class="galeria-item-img" :style="{ backgroundImage: `url('${f.imagen_url}')` }"></div>
          <div class="galeria-item-leyenda">{{ f.eventoNombre }}</div>
        </div>
      </div>
    </div>
  </section>

  <section id="cotizacion" class="py-5 cotiza-section">
    <div class="container" style="max-width: 720px">
      <h2 class="text-center fw-bold mb-2">¿TIENES UN EVENTO EN MENTE?</h2>
      <p class="text-center text-secondary mb-4">Cuéntanos tu idea y te contactamos en menos de 24 horas</p>
      <ContactForm />
    </div>
  </section>

  <ServicioModal ref="servicioModalRef" />
</template>
