// src/pages/Portafolio.tsx
import { useEffect, useState } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { Navbar, Footer, WhatsAppButton } from '@/components/layout';
import { FadeInUp, ParticleBackground } from '@/components/animations';
import { Button, Card, Badge } from '@/components/ui';
import { portafolioService } from '@/services/portafolio.service';
import { Evento, EventoTipo } from '@/types';
import Masonry from 'react-masonry-css';

export const PortafolioLista = () => {
  const [tipos, setTipos] = useState<EventoTipo[]>([]);
  const [eventos, setEventos] = useState<Evento[]>([]);
  const [selectedTipo, setSelectedTipo] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadData = async () => {
      try {
        const [tipos, eventos] = await Promise.all([
          portafolioService.getTipos(),
          portafolioService.getEventos(),
        ]);
        setTipos(tipos);
        setEventos(eventos);
      } catch (error) {
        console.error('Error loading portafolio:', error);
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, []);

  const filteredEventos = selectedTipo
    ? eventos.filter((e) => e.tipo_slug === selectedTipo)
    : eventos;

  if (loading) {
    return (
      <div className="min-h-screen bg-surface flex items-center justify-center">
        <p className="text-muted">Cargando portafolio...</p>
      </div>
    );
  }

  return (
    <>
      <Navbar />
      <WhatsAppButton />

      <section className="relative pt-32 pb-20 bg-surface overflow-hidden">
        <ParticleBackground />
        <div className="relative z-10 max-w-7xl mx-auto px-4 text-center">
          <FadeInUp>
            <h1 className="text-5xl md:text-7xl font-bebas tracking-wider mb-6 text-text">
              PORTAFOLIO
            </h1>
          </FadeInUp>
          <FadeInUp delay={0.2}>
            <p className="text-lg text-muted">
              {eventos.length} eventos realizados con pasión
            </p>
          </FadeInUp>
        </div>
      </section>

      <section className="py-20 bg-surface">
        <div className="max-w-7xl mx-auto px-4">
          <FadeInUp>
            <div className="flex flex-wrap gap-3 justify-center mb-16">
              <button
                onClick={() => setSelectedTipo(null)}
                className={`px-6 py-2 rounded-full font-grotesk transition-all ${
                  selectedTipo === null
                    ? 'gradient-primary text-white'
                    : 'bg-card text-text hover:border-primary border border-border'
                }`}
              >
                Todos
              </button>
              {tipos.map((tipo) => (
                <button
                  key={tipo.id}
                  onClick={() => setSelectedTipo(tipo.slug)}
                  className={`px-6 py-2 rounded-full font-grotesk transition-all ${
                    selectedTipo === tipo.slug
                      ? 'gradient-primary text-white'
                      : 'bg-card text-text hover:border-primary border border-border'
                  }`}
                >
                  {tipo.nombre}
                </button>
              ))}
            </div>
          </FadeInUp>

          <Masonry
            breakpointCols={{ default: 3, 1024: 2, 640: 1 }}
            className="masonry-grid"
            columnClassName="masonry-grid-column"
          >
            {filteredEventos.map((evento) => (
              <FadeInUp key={evento.id}>
                <Link to={`/portafolio/${evento.slug}`}>
                  <Card className="overflow-hidden cursor-pointer h-64">
                    <div
                      className="w-full h-full bg-cover bg-center relative group-hover:scale-105 transition-transform"
                      style={{
                        backgroundImage: `url('${evento.imagen_destacada}')`,
                      }}
                    >
                      <div className="gradient-overlay absolute inset-0 flex flex-col justify-end p-4">
                        <Badge variant="secondary">{evento.tipo_slug}</Badge>
                        <h3 className="text-lg font-grotesk font-bold text-text mt-2">
                          {evento.nombre}
                        </h3>
                        <p className="text-xs text-muted">{evento.lugar}</p>
                      </div>
                    </div>
                  </Card>
                </Link>
              </FadeInUp>
            ))}
          </Masonry>
        </div>
      </section>

      <Footer />
    </>
  );
};

export const PortafolioDetalle = () => {
  const { slug } = useParams<{ slug: string }>();
  const navigate = useNavigate();
  const [evento, setEvento] = useState<Evento | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadEvento = async () => {
      if (!slug) return;
      try {
        const data = await portafolioService.getEventoBySlug(slug);
        setEvento(data);
      } catch (error) {
        console.error('Error loading evento:', error);
      } finally {
        setLoading(false);
      }
    };

    loadEvento();
  }, [slug]);

  if (loading) {
    return (
      <div className="min-h-screen bg-surface flex items-center justify-center">
        <p className="text-muted">Cargando evento...</p>
      </div>
    );
  }

  if (!evento) {
    return (
      <div className="min-h-screen bg-surface flex items-center justify-center">
        <p className="text-muted">Evento no encontrado</p>
      </div>
    );
  }

  return (
    <>
      <Navbar />
      <WhatsAppButton />

      <section className="relative h-96 overflow-hidden">
        <div
          className="w-full h-full bg-cover bg-center"
          style={{
            backgroundImage: `url('${evento.imagen_destacada}')`,
          }}
        >
          <div className="gradient-overlay absolute inset-0 flex flex-col justify-end p-8">
            <Badge variant="secondary" className="w-fit mb-4">
              {evento.tipo_slug}
            </Badge>
            <h1 className="text-5xl font-bebas text-white">{evento.nombre}</h1>
          </div>
        </div>
      </section>

      <div className="max-w-4xl mx-auto px-4 py-20">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
          <Card>
            <h3 className="font-grotesk font-bold text-primary mb-2">Cliente</h3>
            <p className="text-text">{evento.cliente}</p>
          </Card>
          <Card>
            <h3 className="font-grotesk font-bold text-primary mb-2">Ubicación</h3>
            <p className="text-text">{evento.lugar}</p>
          </Card>
          <Card>
            <h3 className="font-grotesk font-bold text-primary mb-2">Asistentes</h3>
            <p className="text-text">{evento.asistentes ? `${evento.asistentes}+` : 'N/A'}</p>
          </Card>
        </div>

        <FadeInUp>
          <div className="mb-16">
            <h2 className="text-3xl font-bebas mb-6 text-primary">Sobre el evento</h2>
            <p className="text-muted leading-relaxed text-lg">{evento.descripcion_larga}</p>
          </div>
        </FadeInUp>

        {evento.fotos && evento.fotos.length > 0 && (
          <FadeInUp delay={0.2}>
            <div className="mb-16">
              <h2 className="text-3xl font-bebas mb-6 text-primary">Galería</h2>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                {evento.fotos.map((foto) => (
                  <a key={foto.id} href={foto.imagen} target="_blank" rel="noopener noreferrer">
                    <Card className="h-48 overflow-hidden cursor-pointer hover:opacity-80 transition">
                      <div
                        className="w-full h-full bg-cover bg-center"
                        style={{ backgroundImage: `url('${foto.imagen}')` }}
                      />
                    </Card>
                  </a>
                ))}
              </div>
            </div>
          </FadeInUp>
        )}

        <FadeInUp delay={0.4}>
          <div className="bg-card border border-border rounded-lg p-8 text-center">
            <h3 className="text-2xl font-bebas text-primary mb-4">¿Quieres un evento así?</h3>
            <p className="text-muted mb-6">Cuéntanos tu idea y crearemos algo especial</p>
            <Button onClick={() => navigate('/#cotizacion')}>
              Solicitar cotización
            </Button>
          </div>
        </FadeInUp>
      </div>

      <Footer />
    </>
  );
};

// frontend-vue/src/views/Portafolio.vue
<script setup lang="ts">
import { onMounted, ref, computed } from 'vue';
import { RouterLink } from 'vue-router';
import FadeInUp from '@/components/animations/FadeInUp.vue';
import ParticleBackground from '@/components/animations/ParticleBackground.vue';
import { portafolioService } from '@/services/portafolio';
import type { Evento, EventoTipo } from '@/types';

const tipos = ref<EventoTipo[]>([]);
const eventos = ref<Evento[]>([]);
const sel = ref<string | null>(null);

const filtrados = computed(() =>
  sel.value ? eventos.value.filter((e) => e.tipo_slug === sel.value) : eventos.value,
);

onMounted(async () => {
  [tipos.value, eventos.value] = await Promise.all([
    portafolioService.getTipos(),
    portafolioService.getEventos(),
  ]);
});
</script>

<template>
  <section class="py-5 text-center position-relative overflow-hidden">
    <ParticleBackground />
    <div class="container position-relative" style="z-index: 1">
      <h1 class="display-4 fw-bold">PORTAFOLIO</h1>
      <p class="text-secondary">{{ eventos.length }} eventos realizados con pasión</p>
    </div>
  </section>

  <section class="py-4">
    <div class="container">
      <div class="d-flex flex-wrap gap-2 justify-content-center mb-4">
        <button class="btn btn-sm" :class="sel === null ? 'btn-orion' : 'btn-outline-light'" @click="sel = null">Todos</button>
        <button v-for="t in tipos" :key="t.id" class="btn btn-sm"
          :class="sel === t.slug ? 'btn-orion' : 'btn-outline-light'" @click="sel = t.slug">
          {{ t.nombre }}
        </button>
      </div>
      <div class="row g-4">
        <div v-for="ev in filtrados" :key="ev.id" class="col-md-6 col-lg-4">
          <FadeInUp>
            <RouterLink :to="`/portafolio/${ev.slug}`" class="text-decoration-none">
              <div class="card border-0 card-cover d-flex justify-content-end"
                :style="{ backgroundImage: `url('${ev.imagen_destacada}')` }">
                <div class="p-3" style="background: linear-gradient(0deg, rgba(0,0,0,0.85), transparent)">
                  <span class="badge text-bg-warning mb-1">{{ ev.tipo_slug }}</span>
                  <h6 class="text-white mb-0">{{ ev.nombre }}</h6>
                  <small class="text-secondary">{{ ev.lugar }}</small>
                </div>
              </div>
            </RouterLink>
          </FadeInUp>
        </div>
      </div>
    </div>
  </section>
</template>
